In [2]:
import numpy as np

# DataTypes & Attributes

In [3]:
# Numpy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a = [1,2,3]
a

[1, 2, 3]

In [6]:
type(a)

list

In [7]:
type(a) == type(a1)

False

In [8]:
a2 = np.array([[1,2.0,3.3],
                [4,5,6.5]])

a3 = np.array([[[1,2,3],
                 [4,5,6],
                 [7,8,9],
                [1.1,1.2,1.3]],
               
                [[10,11,12],
                  [13,14,15],
                  [16,17,18],
                [2.1, 2.2,2.3]]])

In [9]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [10]:
a3

array([[[ 1. ,  2. ,  3. ],
        [ 4. ,  5. ,  6. ],
        [ 7. ,  8. ,  9. ],
        [ 1.1,  1.2,  1.3]],

       [[10. , 11. , 12. ],
        [13. , 14. , 15. ],
        [16. , 17. , 18. ],
        [ 2.1,  2.2,  2.3]]])

In [11]:
a3.shape

(2, 4, 3)

In [12]:
a1.shape

(3,)

In [13]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [14]:
# Create a dataframe from numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

In [15]:
df1 = pd.DataFrame(a3)
df1

ValueError: Must pass 2-d input. shape=(2, 4, 3)

## Creating Arrays

In [17]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [18]:
sample_array.dtype

dtype('int32')

In [19]:
ones = np.ones((2,3))

In [20]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
ones.dtype

dtype('float64')

In [22]:
type(ones)

numpy.ndarray

In [23]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [25]:
random_array = np.random.randint(0, 10, size= (3,5))
random_array

array([[2, 3, 7, 6, 0],
       [0, 2, 6, 0, 9],
       [2, 8, 5, 8, 0]])

In [26]:
random_array.size

15

In [27]:
random_array.shape

(3, 5)

In [28]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.30862182, 0.9200608 , 0.54770495],
       [0.73716313, 0.69348317, 0.56243724],
       [0.57140172, 0.0455179 , 0.4491146 ],
       [0.67990323, 0.34880213, 0.29269049],
       [0.61788632, 0.32350145, 0.17669524]])

In [29]:
random_array_2.shape

(5, 3)

In [30]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.50450655, 0.66896977, 0.02150206],
       [0.5861225 , 0.65186946, 0.89090265],
       [0.49419809, 0.21962919, 0.48250409],
       [0.60766287, 0.23577772, 0.27298256],
       [0.76577581, 0.4693434 , 0.35399039]])

In [31]:
# Pseudo-random numbers
np.random.seed(0)
random_array_4 = np.random.randint(10, size = (5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [32]:
np.random.seed(7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## Viewing arrays and matrices

In [33]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
a1, a2, a3

(array([1, 2, 3]),
 array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]),
 array([[[ 1. ,  2. ,  3. ],
         [ 4. ,  5. ,  6. ],
         [ 7. ,  8. ,  9. ],
         [ 1.1,  1.2,  1.3]],
 
        [[10. , 11. , 12. ],
         [13. , 14. , 15. ],
         [16. , 17. , 18. ],
         [ 2.1,  2.2,  2.3]]]))

In [35]:
a2[0]

array([1. , 2. , 3.3])

In [36]:
a3[0][3]

array([1.1, 1.2, 1.3])

## Manipulating & Comparing Arrays

### Arithmetic

In [37]:
a1

array([1, 2, 3])

In [38]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [39]:
a1 + ones

array([2., 3., 4.])

In [40]:
a1 - ones

array([0., 1., 2.])

In [41]:
a1 * ones

array([1., 2., 3.])

In [42]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [43]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [44]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,4,3) 

In [45]:
# how can we reshape a2 to be compatible with a3? 
# Figure Out

In [46]:
ones / a1

array([1.        , 0.5       , 0.33333333])

In [47]:
a2 ** 2 

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [48]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [49]:
np.add(a1, ones)

array([2., 3., 4.])

In [50]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [51]:
np.mod(a1 , 2)

array([1, 0, 1], dtype=int32)

### Aggregation
aggregation = preforming the same operation on a number things

In [52]:
listy_list = [1,2,3]
type(listy_list)

list

In [53]:
sum(listy_list)

6

In [54]:
np.sum(listy_list)

6

#### Use Python's methods on python datatypes and use numpy's methods on numpy arrays

In [55]:
# Creative a massive Numpy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [56]:
%timeit sum(massive_array) # Python's sum()
%timeit np.sum(massive_array) # Numpy's np.sum()

6.78 ms ± 59.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
39.5 µs ± 196 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [57]:
np.mean(a2)

3.6333333333333333

In [58]:
np.max(a2)

6.5

### Standard deviation = a measure of how spread out a group of numbers is from the mean

In [59]:
np.std(a2)

1.8226964152656422

### Variance = measure of the average degree to which each number is different to the mean
 Higher Variance = wider range of numbers
 Lower Variance = lower range of numbers

In [60]:
np.var(a2)

3.3222222222222224

In [61]:
# Standard deviation = sqaureroot of variance
np.sqrt(np.var(a2))

1.8226964152656422

In [62]:
# Demo of std and var
high_var_array = np.array([1,100, 200, 300, 4000, 5000])
low_var_array = np.array([2,4,6,8,10])

In [63]:
np.var(high_var_array), np.var(low_var_array)

(4296133.472222221, 8.0)

In [64]:
np.std(high_var_array) , np.std(low_var_array)

(2072.711623024829, 2.8284271247461903)

## Reshaping & Transposing

In [65]:
a2, a2.shape

(array([[1. , 2. , 3.3],
        [4. , 5. , 6.5]]),
 (2, 3))

In [66]:
a3, a3.shape

(array([[[ 1. ,  2. ,  3. ],
         [ 4. ,  5. ,  6. ],
         [ 7. ,  8. ,  9. ],
         [ 1.1,  1.2,  1.3]],
 
        [[10. , 11. , 12. ],
         [13. , 14. , 15. ],
         [16. , 17. , 18. ],
         [ 2.1,  2.2,  2.3]]]),
 (2, 4, 3))

In [67]:
a2 * a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,4,3) 

In [73]:
a2 = a2.reshape(2,3,1)

In [69]:
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,4,3) 

In [74]:
a3 = a3.reshape(2,3,4)

In [75]:
a2.shape, a3.shape

((2, 3, 1), (2, 3, 4))

In [76]:
a2*a3

array([[[  1.  ,   2.  ,   3.  ,   4.  ],
        [ 10.  ,  12.  ,  14.  ,  16.  ],
        [ 29.7 ,   3.63,   3.96,   4.29]],

       [[ 40.  ,  44.  ,  48.  ,  52.  ],
        [ 70.  ,  75.  ,  80.  ,  85.  ],
        [117.  ,  13.65,  14.3 ,  14.95]]])

In [77]:
# Transpose
a2, a2.shape

(array([[[1. ],
         [2. ],
         [3.3]],
 
        [[4. ],
         [5. ],
         [6.5]]]),
 (2, 3, 1))

In [78]:
a2.T, a2.T.shape

(array([[[1. , 4. ],
         [2. , 5. ],
         [3.3, 6.5]]]),
 (1, 3, 2))

## Dot Product 

In [79]:
np.random.seed(0)

mat1 = np.random.randint(10, size=(5,3))
mat2 = np.random.randint(10, size=(5,3))


In [80]:
mat1, mat2

(array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6],
        [8, 8, 1]]),
 array([[6, 7, 7],
        [8, 1, 5],
        [9, 8, 9],
        [4, 3, 0],
        [3, 5, 0]]))

In [81]:
# ELement-wise multiplication (Hadamard Product)
mat1*mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [82]:
# Dot Product
np.dot(mat1, mat2)

ValueError: shapes (5,3) and (5,3) not aligned: 3 (dim 1) != 5 (dim 0)

In [83]:
np.dot(mat1.T, mat2)

array([[121, 114,  77],
       [153, 108,  80],
       [135,  69,  84]])

# Dot Product Example
### Nut Butter Sales

In [94]:
np.random.seed(0)
# Number of jars sold
sales_amounts = np.random.randint(20, size=(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [95]:
# Create weekly_sales DataFrame
weekly_sales = pd.DataFrame(sales_amounts, index=["Mon", "Tue", "Wed", "Thu", "Fri"],
                           columns=["Almond butter", "Peanut butter", "Cashew butter"])

weekly_sales

Almond butter  Peanut butter  Cashew butter
Mon             12             15              0
Tue              3              3              7
Wed              9             19             18
Thu              4              6             12
Fri              1              6              7

In [96]:
# Create the prices array
prices = np.array([10,8,12])
prices

array([10,  8, 12])

In [97]:
# Create butter prices dataFrame
butter_prices = pd.DataFrame(prices.reshape(1,3), index=["Price"], 
                             columns=["Almond butter", "Peanut butter", "Cashew butter"])
butter_prices

Almond butter  Peanut butter  Cashew butter
Price             10              8             12

In [98]:
weekly_sales.shape, butter_prices.shape

((5, 3), (1, 3))

In [99]:
weekly_sales["Total($)"] = np.dot(weekly_sales, butter_prices.T)
weekly_sales

Almond butter  Peanut butter  Cashew butter  Total($)
Mon             12             15              0       240
Tue              3              3              7       138
Wed              9             19             18       458
Thu              4              6             12       232
Fri              1              6              7       142

## Comparison Operators

In [100]:
a1, a2

(array([1, 2, 3]),
 array([[[1. ],
         [2. ],
         [3.3]],
 
        [[4. ],
         [5. ],
         [6.5]]]))

In [104]:
a1 > a2

array([[[False,  True,  True],
        [False, False,  True],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False]]])

In [105]:
a1 < 5

array([ True,  True,  True])

In [106]:
a1 == a2

array([[[ True, False, False],
        [False,  True, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False]]])

## Sorting arrays

In [107]:
random_array

array([[2, 3, 7, 6, 0],
       [0, 2, 6, 0, 9],
       [2, 8, 5, 8, 0]])

In [108]:
np.sort(random_array)

array([[0, 2, 3, 6, 7],
       [0, 0, 2, 6, 9],
       [0, 2, 5, 8, 8]])

In [110]:
random_array

array([[2, 3, 7, 6, 0],
       [0, 2, 6, 0, 9],
       [2, 8, 5, 8, 0]])

In [109]:
np.argsort(random_array)

array([[4, 0, 1, 3, 2],
       [0, 3, 1, 2, 4],
       [4, 0, 2, 1, 3]], dtype=int64)

In [116]:
np.argmin(random_array, axis=0)

array([1, 1, 2, 1, 0], dtype=int64)

In [117]:
np.argmin(random_array, axis=1)

array([4, 0, 4], dtype=int64)

In [115]:
np.argmax(random_array, axis=0)

array([0, 2, 0, 2, 1], dtype=int64)

In [113]:
a1

array([1, 2, 3])

In [114]:
np.argmax(a1), np.argmin(a1)

(2, 0)

## Practical Example

In [119]:
# Turn an image into a Numpy array
from matplotlib.image import imread

panda = imread("images/panda.png")

In [121]:
type(panda)

numpy.ndarray

In [122]:
panda.size, panda.shape

(24465000, (2330, 3500, 3))